// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukdtrelzqsbcrqfbanjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZHRyZWx6cXNiY3JxZmJhbmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDI2MjgsImV4cCI6MjA2NDgxODYyOH0.Hh9TpgJHO3eHgXB6zGm18mcwqd26Lg621R17QofZWsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);